#==============================================================================
# vim: softtabstop=2 shiftwidth=2 expandtab fenc=utf-8 cc=81 tw=80
#==============================================================================
#
# DESCRIPTION: Debian base image for docker built with docker.
#
#==============================================================================
---
extend: ../base/debian.yaml
# Enables qcow2 checkpoint
# checkpoint: docker.yaml
#== Global variables use by Kameleon engine and the steps
global:
  # Distribution
  release: wheezy

  ## Docker options
  docker_dns: 208.67.222.222
  docker_image: $$kameleon_recipe_name
  docker_hostname: $$kameleon_recipe_name

  # rootfs options
  rootfs: $$kameleon_cwd/rootfs

  # Shell session from where we launch exec_out commands. There is often a
  # local bash session, but it can be a remote shell on other machines or on
  # any shell. (eg. bash, chroot, fakechroot, ssh, tmux, lxc...)
  out_context:
    cmd: bash
    workdir: $$kameleon_cwd
    proxy_cache: localhost

  # Shell session that allows us to connect to the building machine in order to
  # configure it and setup additional programs
  ssh_config_file: $$kameleon_cwd/ssh_config
  in_context:
    cmd: LC_ALL=POSIX ssh -F $$ssh_config_file $$kameleon_recipe_name -t /bin/bash
    workdir: /root/kameleon_workdir
    proxy_cache: 172.17.42.1

  bootstrap_packages: >
    bsdutils ca-certificates locales man-db less libui-dialog-perl dialog
    isc-dhcp-client ifupdown iptables iputils-ping iproute netbase net-tools
    psmisc openssh-server

  setup_packages: >
    sudo vim bash-completion curl bzip2 dialog


#== Bootstrap the new system and create the 'in_context'
bootstrap:
  - "@base"
  - prepare_docker
  - start_docker


#== Install and configuration steps
# WARNING: this part should be independante from the out context (whenever
# possible...)
setup:
  - configure_apt:
    - repository: $$apt_repository
    - enable_contrib_repo: $$apt_enable_contrib
    - enable_nonfree_repo: $$apt_enable_nonfree
  - upgrade_system:
    - dist_upgrade: true
  - install_software:
    - packages: >
        debian-keyring $$setup_packages lxc
  # Configuration
  - configure_system:
    - locales: POSIX C en_US fr_FR de_DE
    - lang: en_US.UTF-8
    - timezone: UTC
  - configure_network
  - configure_container

#== Export the generated appliance in the format of your choice
export:
  - save_docker_appliance:
    - save_as_targz:
      - exec_out: mkdir $$kameleon_cwd/tmpfs/
      - exec_out: docker export $(cat MAIN_CONTAINER_ID) | tar xf - -C $$kameleon_cwd/tmpfs/
      - exec_out: mknod -m 666 $$kameleon_cwd/tmpfs/dev/tty1 c 4 1
      - exec_out: mknod -m 666 $$kameleon_cwd/tmpfs/dev/tty2 c 4 2
      - exec_out: mknod -m 666 $$kameleon_cwd/tmpfs/dev/tty3 c 4 3
      - exec_out: mknod -m 666 $$kameleon_cwd/tmpfs/dev/tty4 c 4 4
      - exec_out: tar -zcf $$kameleon_cwd/$$kameleon_recipe_name.tar.gz -C $$kameleon_cwd/tmpfs/ .
      - exec_out: rm -rf $$kameleon_cwd/tmpfs
