- create_iniittab:
  - write_in:
    - /etc/inittab
    - |
      id:3:initdefault:
      si::sysinit:/etc/init.d/rcS
      l0:0:wait:/etc/init.d/rc 0
      l1:1:wait:/etc/init.d/rc 1
      l2:2:wait:/etc/init.d/rc 2
      l3:3:wait:/etc/init.d/rc 3
      l4:4:wait:/etc/init.d/rc 4
      l5:5:wait:/etc/init.d/rc 5
      l6:6:wait:/etc/init.d/rc 6
      # Normally not reached, but fallthrough in case of emergency.
      z6:6:respawn:/sbin/sulogin
      1:2345:respawn:/sbin/getty 38400 console
      c1:12345:respawn:/sbin/getty 38400 tty1 linux
      c2:12345:respawn:/sbin/getty 38400 tty2 linux
      c3:12345:respawn:/sbin/getty 38400 tty3 linux
      c4:12345:respawn:/sbin/getty 38400 tty4 linux
      p6::ctrlaltdel:/sbin/init 6
      p0::powerfail:/sbin/init 0

- remove_useless_services:
  - exec_in: /usr/sbin/update-rc.d -f checkroot.sh remove
  - exec_in: /usr/sbin/update-rc.d -f umountfs remove
  - exec_in: /usr/sbin/update-rc.d -f hwclock.sh remove
  - exec_in: /usr/sbin/update-rc.d -f hwclockfirst.sh remove

- configure_systemd:

  - exec_in: |
      if [ -f /lib/systemd/system/getty\@.service ]; then
         sed -e 's/^ConditionPathExists=/# ConditionPathExists=/' \
         -e 's/After=dev-%i.device/After=/' \
         < /lib/systemd/system/getty\@.service \
         > /etc/systemd/system/getty\@.service
      fi

  - exec_in: mkdir -p /{lib,etc}/systemd/system
  - exec_in: mkdir -p /etc/systemd/system/getty.target.wants
  - exec_in: ln -s /dev/null /etc/systemd/system/udev.service
  - exec_in: ln -s /dev/null /etc/systemd/system/systemd-udevd.service
  - exec_in: ln -s /lib/systemd/system/multi-user.target /etc/systemd/system/default.target
  - exec_in: ln -s /lib/systemd/system/halt.target /etc/systemd/system/sigpwr.target
  - exec_in: |
      ( cd /etc/systemd/system/getty.target.wants
      for i in 1 2 3 4 ; do ln -sf ../getty\@.service getty@tty${i}.service; done )
